## USAGE:
## ================================================================================================
# [rpc]: Settings for the RPC client used to communicate with the node
#   - endpoint: tuple indicating the protocol (http, https), the host, and the port where the node is listening.
# [store]: Settings for the client's Store
#   - database_filepath: path for the sqlite's database
[rpc]
endpoint = { protocol = "http", host = "localhost", port = 57291 }
timeout = 10000

[store]
database_filepath = "store.sqlite3"